ValidateName always prints empty string as value instead of actual value (#1646)
This commit fixes an rather annoying issue where `ValidateName` does not
print the correct value of the invalid cluster name which made the issue
hard to debug.

Background:
I recently upgraded from an earlier KubeOne version to master and my cluster-name contained dots (`.`).
However since https://github.com/kubermatic/kubeone/pull/1641 this is no longer valid.

The output of this validation looked like

```bash
$ kubeone apply --manifest kubeone.yaml --credentials credentials.yaml --tfjson output.json --auto-approve --verbose

Error: failed to initialize State: failed to build state: failed to load cluster: unable to load a given KubeOneCluster object: unable to validate the given KubeOneCluster object: name: Invalid value: "": .name should be lowercase and can only contain alphanumeric characters and hyphens(-)
```

With this commit in place the output looks like this:

```bash
$ kubeone install --manifest kubeone.yaml --credentials credentials.yaml --tfjson output.json --verbose
Error: failed to initialize State: failed to build state: failed to load cluster: unable to load a given KubeOneCluster object: unable to validate the given KubeOneCluster object: name: Invalid value: "k8s.cedi.dev": .name should be lowercase and can only contain alphanumeric characters and hyphens(-)
```

Signed-off-by: Cedric Kienzler <github@cedric-kienzler.de>